name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy script
        run: |
          mkdir -p deb/usr/local/bin
          cp genpw.sh deb/usr/local/bin/genpw
          chmod +x deb/usr/local/bin/genpw

      - name: Build deb
        run: |
          dpkg-deb --build --root-owner-group deb

      - name: Rename deb
        run: mv deb.deb genpw_$(dpkg-deb -f deb.deb Version)_$(dpkg-deb -f deb.deb Architecture).deb

      - name: Upload deb
        uses: actions/upload-artifact@v2
        with:
          name: debian-genpw
          path: "*.deb"
